// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210617165506_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("BirthWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DamId")
                        .HasColumnType("int");

                    b.Property<string>("EarTag")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<decimal?>("IncomeWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SireId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DamId");

                    b.HasIndex("FarmId");

                    b.HasIndex("SireId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Domain.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(2342),
                            Name = "-No Asignado-"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5196),
                            Name = "Angus"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5206),
                            Name = "Angus Negro"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5208),
                            Name = "Angus Rojo"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5209),
                            Name = "Ayrshire"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5210),
                            Name = "Bom"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5211),
                            Name = "Brahman"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5212),
                            Name = "Brangus"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5213),
                            Name = "Casanareño"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5214),
                            Name = "Cebu"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5216),
                            Name = "Charolais"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5217),
                            Name = "Chino Santandereano"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5218),
                            Name = "Costeño con Cuernos"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5219),
                            Name = "Criollo"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5220),
                            Name = "Guzerat"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5221),
                            Name = "Gyr"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5222),
                            Name = "Harton del valle"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5223),
                            Name = "Holstein"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5224),
                            Name = "Indubrasil"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5225),
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5227),
                            Name = "Limousin"
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5228),
                            Name = "Lucerna"
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5229),
                            Name = "Nelore"
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5230),
                            Name = "Normando"
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5231),
                            Name = "Pardo"
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5232),
                            Name = "Romosinuano"
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5233),
                            Name = "Sanmartinero"
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5234),
                            Name = "Simmental"
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 363, DateTimeKind.Local).AddTicks(5235),
                            Name = "Velasquez"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 364, DateTimeKind.Local).AddTicks(6538),
                            CreatedBy = "system",
                            Name = "Crias"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 364, DateTimeKind.Local).AddTicks(6781),
                            CreatedBy = "system",
                            Name = "Novillas"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 364, DateTimeKind.Local).AddTicks(6785),
                            CreatedBy = "system",
                            Name = "Mautes"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 364, DateTimeKind.Local).AddTicks(6786),
                            CreatedBy = "system",
                            Name = "Vacas"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 364, DateTimeKind.Local).AddTicks(6788),
                            CreatedBy = "system",
                            Name = "Toros"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Santa Rosa de Lima, paralelo 38",
                            Code = "ARZ",
                            Created = new DateTime(2021, 6, 17, 11, 55, 6, 365, DateTimeKind.Local).AddTicks(4107),
                            Name = "Hacienda Arizona Y Villa Monica",
                            Phone = "3000000000"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.HasOne("Domain.Entities.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Animal", "Dam")
                        .WithMany("DamPups")
                        .HasForeignKey("DamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Animal", "Sire")
                        .WithMany("SirePups")
                        .HasForeignKey("SireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Breed");

                    b.Navigation("Category");

                    b.Navigation("Dam");

                    b.Navigation("Farm");

                    b.Navigation("Sire");
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Navigation("DamPups");

                    b.Navigation("SirePups");
                });
#pragma warning restore 612, 618
        }
    }
}
